# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :tests do
  run_tests(scheme: "ExamWorkTest")
end

platform :ios do
      desc "My awesome app"
      lane :distribute do
          build_ios_app(
  		workspace: "ExamWork.xcworkspace",
  		configuration: "Debug",
  		scheme: "ExamWork",
		export_method: "development")

          firebase_app_distribution(
              app: "1:556533596256:ios:f9d06990f893f4a5ca4305",
              testers: "tester1@company.com, tester2@company.com",
              release_notes: "Lots of amazing new features to test out!",
              firebase_cli_path: "/usr/local/bin/firebase"
          )

      end
  end

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
