# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExamWork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExamWork
	pod 'Firebase/Analytics'
  target 'ExamWorkTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Firebase/Analytics'
  end

  target 'ExamWorkUITests' do
    # Pods for testing
	pod 'Firebase/Analytics'
  end

end
